spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ctw_todo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 9000